#! /bin/bash

#EDIT YOUR STAGING CREDENTIALS HERE
staginghost=""
stagingpswd=""
staginguser=""

#EDIT YOUR PRODUCTION CREDENTIALS HERE
develophost=""
developpswd=""
developuser=""

#DONT TOUCH THIS
echo "Do you want to init the project? [yes or no]"
read init

echo "Where to deploy? [staging or dev]"
read environment

if [ "$init" == "yes" ]; then
	if [ "$environment" == "staging" ]; then
		git ftp init -u "$staginguser" -P "$staginghost"
	fi
	if [ "$environment" == "dev" ]; then
		git ftp init -u "$developuser" -P "$develophost"
	fi
fi

if [ "$init" == "no" ]; then
	if [ "$environment" == "staging" ]; then
		git ftp push --user "$staginguser" --passwd "$stagingpswd" "$staginghost"
	fi
	if [ "$environment" == "dev" ]; then
		git ftp push --user "$developuser" --passwd "$developpswd" "$develophost"
	fi
fi

if [ "$init" == "yes" ]; then
	echo init to $environment;
else
	echo update to $environment;
fi